---
- name: Install and configure web and database servers
  hosts: webservers
  become: true

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Change Apache to listen on port 8080
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: 'Listen 8080'

    - name: Update Apache default virtual host to port 8080
      replace:
       path: /etc/apache2/sites-available/000-default.conf
       regexp: '(<VirtualHost\s+\*:)80'
       replace: '\g<1>8080'

    - name: Restart Apache to apply port change
      service:
        name: apache2
        state: restarted
        enabled: yes

    - name: Start and enable MySQL
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

