---
- name: Create user and add to group
  hosts: all
  become: true  # Run with sudo privileges
  tasks:
    - name: Ensure the group 'developers' exists
      group:
        name: developers
        state: present

    - name: Create user 'johndoe' and add to 'developers' group
      user:
        name: johndoe
        shell: /bin/bash
        groups: developers
        append: yes
        state: present

