---
- name: Install multiple packages
  hosts: all
  become: yes
  vars:
    package_list:
      - git
      - curl
      - htop
      - vim

  tasks:
    - name: Ensure required packages are installed
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ package_list }}"

