- name: System maintenance playbook
  hosts: all
  become: yes
  tasks:

    - name: Install nginx on Debian
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install httpd on RedHat
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Remove unnecessary packages
      package:
        name: "{{ item }}"
        state: absent
      loop:
        - nginx
        - httpd

    - name: Configure static IP on RedHat
      nmcli:
        conn_name: "eth0"
        ifname: "eth0"
        type: ethernet
        ip4: 192.168.1.100/24
        gw4: 192.168.1.1
        state: present
      when: ansible_os_family == "RedHat"

    - name: Update all packages on Debian
      apt:
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update all packages on RedHat
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Reboot the server
      reboot:
        reboot_timeout: 600

