- name: Configure or verify S3 usage on remote servers
  hosts: all
  gather_facts: yes  # Enables OS detection
  become: true

  vars:
    bucket_name: sandeep-unique-bucket-002
    region: ap-south-1

  tasks:
    - name: Install unzip (Ubuntu/Debian)
      apt:
        name: unzip
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install unzip (RHEL/CentOS/Amazon Linux)
      yum:
        name: unzip
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Download AWS CLI v2 installer
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip
        mode: '0644'

    - name: Unzip AWS CLI installer
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Install AWS CLI
      shell: /tmp/aws/install
      args:
        creates: /usr/local/bin/aws

    - name: Verify AWS CLI installed
      shell: aws --version
      register: aws_cli_version

    - name: Show AWS CLI version
      debug:
        var: aws_cli_version.stdout

